repos:
  - repo: local
    hooks:
      - id: black-formatter
        name: Format Python with Black
        entry: make format
        language: system
        types: [python]
      - id: relock
        name: Regenerate Pipfile.lock
        entry: pipenv lock
        language: system
        files: ^Pipfile$
