version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie

    steps:
      - checkout

      - run:
          name: Setup Env
          command: |
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            sudo chmod 777 -R /usr/local/bin

      - run:
          name: Install Dependencies
          command: |
            make bootstrap
            make clean-env
            make install-deploy-dev

      - run:
          name: Lint
          command: make lint

      - run:
          name: Unit Tests
          command: make test

      - store_test_results:
          path: test-results
