version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie

    environment:
       BASH_ENV: ~/.bashrc

    steps:
      - checkout

      - run:
          name: Setup Env
          command: |
            touch $BASH_ENV
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install Dependencies
          command: |
            make bootstrap
            make install-deploy-dev

      - run:
          name: Lint
          command: make lint

      - run:
          name: Unit Tests
          command: make test
