version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-jessie

    steps:
      - checkout

      - run:
          name: Setup Env
          command: |
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            sudo chmod 777 -R /usr/local/bin

      - run:
          name: Install Dependencies
          command: |
            make bootstrap
            make clean-env
            make install-deploy-dev

      - run:
          name: Lint
          command: make lint

      - run:
          name: Unit Tests
          command: make test

      - store_test_results:
          path: test-results

  fake_deploy:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Test
          command: |
            export

  fake_deploy_2:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Test
          command: |
            export

workflows:
  version: 2
  normal_workflow:
    jobs:
      - build
  deploy_workflow:
    jobs:
      - fake_deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - fake_deploy_2:
          requires:
            - fake_deploy
