version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.5-jessie-browsers
     steps:
       - checkout
       - run: make bootstrap
       - run: make install
       - run: make lint
       - run: make test
